### ISSUE TITLE
Dynamical Expansion of DER

### ISSUE THREAD

**Issue by HenryZ94264** [G-U-N/PyCIL#11]
Hello, you did an excellent job and thanks for your contribution.
But at the DER learner, I can't find the code of Dynamical Expansion, did you implement this part of DER?

**Comment by G-U-N** [comment]
Thanks for your interest! 
Do you mean the pruning stage by saying `Dynamical Expansion`? We didn't implement this since the official implementation also lacks this part.  The reason behind that might be the pruning stage in DER is hyperparameter sensitive and we wouldn't get the ideal performance without careful hyperparameter tuning. 
You can refer to the implementation of [HAT](https://github.com/joansj/hat) for more details about the pruning method.  We might add this pruning stage to the toolbox if we have time in the future.
