### ISSUE TITLE
Single GPU training error in DER

### ISSUE THREAD

**Issue by htwang14** [G-U-N/PyCIL#13]
Hi, 

Thank you for this wonderful code base! 

I noticed the current version doesn't support single GPU training. Could you please add this feature?

Thank you!

**Comment by G-U-N** [comment]
Would you mind sharing the error logs? 
Ideally(i.e., without encountering bugs), change the original params in JSON files
```json
"device": ["0","1","2","3"],
```
to 
```json
"device": ["0"]
```
, and you can run the algos with single GPU.

**Comment by htwang14** [comment]
I haven't tried other methods, but for DER, something like this might be necessary: https://github.com/htwang14/PyCIL/commit/e15cbe5f766b3d5603c115afb0523020114ed128

**Comment by G-U-N** [comment]
Thanks,  I have fixed the problem.
The error occurs because of the lack of judgment on whether self._network is an instance of `module` or  `DataParallel` in function [`train(self)`](https://github.com/G-U-N/PyCIL/blob/c2cd3ebb99f5a05ac2f30bed0e5875eed04cdcaa/models/der.py#L84).  Here, I create a module pointer (i.e., the self._network_module_ptr) which always points to the module instance. 
```python
    def train(self):
        self._network.train()
        if len(self._multiple_gpus) > 1 :
            self._network_module_ptr = self._network.module
        else:
            self._network_module_ptr = self._network
        self._network_module_ptr.convnets[-1].train()
        if self._cur_task >= 1:
            for i in range(self._cur_task):
                self._network_module_ptr.convnets[i].eval()
```
Hope this can help you.
