### ISSUE TITLE
Missing parameters leading to incorrect code behavior

### ISSUE THREAD

**Issue by nttung1110** [G-U-N/PyCIL#36]
Hi,

Thanks for your interesting work. I tried to run the cil benchmark on different setting (i.e. different number of classes being learnt for each task). In the evaluation code models/base.py, it seems like you forgot to pass the important parameter "increment" to be processed by the accuracy function inside utils/toolkit.py. 

This leads to incorrect behavior of the codebase which always compute the evaluation on only one setting (i.e. 10 classes at a time). Could you please check it again? Thanks!

<img width="502" alt="image" src="https://user-images.githubusercontent.com/40194928/229112512-0c018da1-d579-4d74-90e2-455ff0eba135.png">

**Comment by G-U-N** [comment]
Hi,

Thank you for bringing this issue to our attention. Regarding your question, the computed `all_acc` dictionary in `toolkit.py` contains the accuracy metrics for `all`, `old`, and `new classes` respectively, which are already adequate for us to evaluate the performance of all incremental settings. The default value of increment here is 10 because we want to observe the changes in the average accuracy of every ten categories. You can directly set the value to 1 for a more detailed observation.

**Comment by nttung1110** [comment]
Hi @G-U-N ,

Thanks for your response. I tried to run through different settings and observe the results from all_acc dictionary but it returned the same set of dictionary keys (i.e. the range of class idx "start-end"). The keys are expected to be appropriate with the class idx for each setting (different number of classes per task). Anyway, thanks for your great support.
![image](https://user-images.githubusercontent.com/40194928/229338183-1147ad9c-4368-4589-8b9e-bcc794691aee.png)
